nelmio_api_doc:
    documentation:
        info:
            title: "Documents File API"
            description: "Document"
            version: 1.0.0

    areas: # to filter documented areas
        default:
            name_patterns: [ ^api_? ]

    models:
        use_jms: true
